# Generated by Django 3.2.15 on 2022-12-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221221_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.link', verbose_name='Ссылка'),
        ),
    ]
