# Generated by Django 3.2.15 on 2022-12-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221221_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
    ]
