# Generated by Django 3.2.15 on 2022-12-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221221_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='book',
            new_name='book_a',
        ),
    ]
